#!/bin/sh
set -e

# ═══════════════════════════════════════════════════════════════
# openDesk SME — Synapse homeserver.yaml generator
# ═══════════════════════════════════════════════════════════════
# Runs at container startup. Generates homeserver.yaml from
# environment variables.
# ═══════════════════════════════════════════════════════════════

DATA_DIR="/data"
CONFIG_FILE="${DATA_DIR}/homeserver.yaml"
SIGNING_KEY_FILE="${DATA_DIR}/signing.key"

# Generate secrets (persisted in /data)
MACAROON_SECRET_KEY="$(cat "${DATA_DIR}/macaroon_secret_key" 2>/dev/null || openssl rand -hex 32)"
echo "$MACAROON_SECRET_KEY" > "${DATA_DIR}/macaroon_secret_key"

REGISTRATION_SECRET="$(cat "${DATA_DIR}/registration_secret" 2>/dev/null || openssl rand -hex 32)"
echo "$REGISTRATION_SECRET" > "${DATA_DIR}/registration_secret"

if [ ! -f "$SIGNING_KEY_FILE" ]; then
  /usr/local/bin/generate_signing_key.py -o "$SIGNING_KEY_FILE" 2>/dev/null \
    || python3 -c "from signedjson.key import generate_signing_key; generate_signing_key('$SIGNING_KEY_FILE')" 2>/dev/null \
    || openssl genrsa 2048 > "$SIGNING_KEY_FILE" 2>/dev/null
fi

PUBLIC_BASEURL="https://matrix.${DOMAIN:-opendesk-sme.org}"

cat > "$CONFIG_FILE" <<SYNAPSE_EOF
# Generated by opendesk-compose synapse entrypoint
# DO NOT EDIT — regenerated on container start

server_name: "${SYNAPSE_SERVER_NAME:-matrix.${DOMAIN:-opendesk-sme.org}}"
pid_file: /data/homeserver.pid
public_baseurl: "${PUBLIC_BASEURL}"

listeners:
  - type: http
    port: 8008
    bind_addresses: ['0.0.0.0']
    resources:
      - names: [client, federation]
        compress: false
    x_forwarded: true

  - type: metrics
    port: 9000
    bind_addresses: ['0.0.0.0']
    resources:
      - names: [metrics]
    x_forwarded: false

database:
  name: psycopg2
  args:
    user: "${POSTGRES_USER:-synapse_user}"
    password: "${POSTGRES_PASSWORD}"
    database: "${POSTGRES_DB:-synapse_db}"
    host: "${POSTGRES_HOST:-postgres}"
    port: ${POSTGRES_PORT:-5432}
    cp_min: 5
    cp_max: 10

log_config: "/data/log.config"
media_store_path: "/data/media_store"
registration_shared_secret: "${REGISTRATION_SECRET}"
report_stats: false
macaroon_secret_key: "${MACAROON_SECRET_KEY}"
signing_key_path: "${SIGNING_KEY_FILE}"

app_service_config_files: []
federation_custom_pem_certificate: ""

# OIDC (Zitadel) — uncomment and configure for SSO
# oidc_providers:
#   - idp_id: "zitadel"
#     idp_name: "Zitadel"
#     issuer: "https://${ZITADEL_DOMAIN:-auth.opendesk-sme.org}"
#     client_id: "synapse"
#     client_secret: "${SYNAPSE_OIDC_CLIENT_SECRET}"
#     scopes: ["openid", "profile"]
#     user_mapping_provider:
#       module: "synapse.handlers.oidc_handler.OidcAuthenticator"
#       config:
#         localpart_template: "{{ user.preferred_username }}"
#         display_name_template: "{{ user.name }}"
SYNAPSE_EOF

# Generate log config
cat > "${DATA_DIR}/log.config" <<LOG_EOF
version: 1
formatters:
  precise:
    format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(message)s'
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    filename: /data/homeserver.log
    maxBytes: 10485760
    backupCount: 10
    formatter: precise
    encoding: utf8
root:
  level: INFO
  handlers: [file]
disable_existing_loggers: false
LOG_EOF

echo "✅ Synapse config generated: ${CONFIG_FILE}"
