#!/usr/bin/env bash
# dispatch.sh — worker dispatch for taskfleet.
#
# Fills the worker prompt template with task details and runs `pi` headless
# inside the task's worktree. On retry, injects previous failure context so the
# agent can learn from its mistakes.

# shellcheck source=common.sh
. "$(dirname "${BASH_SOURCE[0]}")/common.sh"
# shellcheck source=status.sh
. "$(dirname "${BASH_SOURCE[0]}")/status.sh"
# shellcheck source=worktree.sh
. "$(dirname "${BASH_SOURCE[0]}")/worktree.sh"
# shellcheck source=verify.sh
. "$(dirname "${BASH_SOURCE[0]}")/verify.sh"
# shellcheck source=receipt.sh
. "$(dirname "${BASH_SOURCE[0]}")/receipt.sh"
# shellcheck source=schedule.sh
. "$(dirname "${BASH_SOURCE[0]}")/schedule.sh"
# shellcheck source=cache.sh
. "$(dirname "${BASH_SOURCE[0]}")/cache.sh"
# shellcheck source=episodic.sh
. "$(dirname "${BASH_SOURCE[0]}")/episodic.sh"
# shellcheck source=complexity.sh
. "$(dirname "${BASH_SOURCE[0]}")/complexity.sh"
# shellcheck source=trust.sh
. "$(dirname "${BASH_SOURCE[0]}")/trust.sh"
# shellcheck source=transparency.sh
. "$(dirname "${BASH_SOURCE[0]}")/transparency.sh"
# shellcheck source=constitution.sh
. "$(dirname "${BASH_SOURCE[0]}")/constitution.sh"
# shellcheck source=corrections.sh
. "$(dirname "${BASH_SOURCE[0]}")/corrections.sh"

# tf_select_template <task_id> <worker> → returns the template filename.
# Selects template based on engine field and provider.
tf_select_template() {
  local id="$1" worker="$2" engine provider template
  engine="$(tf_task_field "$id" .engine 2>/dev/null || echo '')"
  
  # Determine provider if worker is specified
  if [[ -n "$worker" && "$worker" != "null" ]]; then
    provider="$(tf_worker_field "$worker" .provider 2>/dev/null || echo '')"
  fi
  
  # Select template based on engine
  case "$engine" in
    content-deep-dive|content-practice-questions)
      # Check if using vllm provider
      if [[ "$provider" == "vllm" ]]; then
        template="content-worker-vllm.md"
      else
        template="content-worker.md"
      fi
      ;;
    content-scenario-challenges)
      template="scenario-worker.md"
      ;;
    security)
      template="scs-security-worker.md"
      ;;
    dev-agent)
      template="dev-agent-worker.md"
      ;;
    sogo6)
      template="sogo6-worker.md"
      ;;
    content-*)
      # Generic content- prefix
      if [[ "$provider" == "vllm" ]]; then
        template="content-worker-vllm.md"
      else
        template="content-worker.md"
      fi
      ;;
    *)
      # Default template
      template="worker.md"
      ;;
  esac
  
  echo "$template"
}

# tf_render_prompt <task_id> [<worker>] → prints filled prompt to stdout.
# Uses bash parameter expansion (NOT envsubst) so only our explicit {{VAR}}
# placeholders are replaced — avoids clobbering literal $1 or template syntax.
# On retry (attempts > 0), injects {{PREVIOUS_ERROR}} with the last failure's
# classified error + relevant log excerpt.
# If worker is provided, it's used for provider detection in template selection.
tf_render_prompt() {
  local id="$1" worker="${2:-}" title engine section accept scope_block tmpl
  local task_group task_project task_change
  title="$(tf_task_field "$id" .title)"
  engine="$(tf_task_field "$id" .engine)"
  section="$(tf_task_field "$id" .section)"
  accept="$(tf_task_field "$id" .accept)"
  scope_block="$(tf_task_field "$id" '.scope[]' | sed 's/^/  /')"
  local plan_section="section $section"
  # OpenSpec fields (optional — present when generated by openspec-bridge.sh)
  task_group="$(tf_task_field "$id" .group 2>/dev/null || echo '')"
  task_project="$(tf_task_field "$id" .project 2>/dev/null || echo '')"
  task_change="$(tf_task_field "$id" .change 2>/dev/null || echo '')"

  # Build error feedback block for retries
  local error_block=""
  local attempts
  attempts="$(tf_status_get "$id" .attempts 2>/dev/null || echo 0)"
  if [[ "$attempts" -gt 0 ]]; then
    local category summary last_error attempt_n
    category="$(tf_get_error_category "$id")"
    summary="$(tf_get_error_summary "$id")"
    last_error="$(tf_status_get "$id" .last_error)"
    attempt_n="$((attempts + 1))"

    # Build structured feedback
    error_block="
## ⚠️ RETRY — attempt $attempt_n (previous attempt failed)

**Error classification:** $category
**Summary:** $summary
**Gate output:** $last_error

The last error log from the acceptance gate is included below. Study it carefully
and fix the root cause. Do NOT repeat the same mistake.

\`\`\`
$(tf_error_snippet "$TF_LOG_DIR/$id.verify.log" 2>/dev/null | head -40)
\`\`\`

"

    # Category-specific retry blocks (gap-aware retry with self-correction few-shot)
    case "$category" in
      no_op)
        # The agent produced no changes last time. Be very explicit.
        local scope_files
        scope_files="$(tf_task_field "$id" '.scope[]' | sed 's/^/  - /')"
        error_block+="
## ⚠️ CRITICAL — Previous attempt produced ZERO changes

You MUST modify the following files. This is not optional. Do not just read them
or analyze them — you must write actual code changes:

$([ -n "$scope_files" ] && echo "$scope_files" || echo "  (check scope in task definition)")

Use your file editing tools to make the required changes. The acceptance gate
will REJECT your work if no files are modified. Do NOT exit without making changes.

"
        ;;
      timeout)
        # The agent ran out of time. Focus on the most important file.
        local primary_scope
        primary_scope="$(tf_task_field "$id" '.scope[0]' 2>/dev/null || echo '')"
        if [[ -n "$primary_scope" ]]; then
          error_block+="
## ⚠️ Previous attempt timed out

Focus on the primary file: $primary_scope. If the task is too large, implement
the core functionality first and add tests, then iterate if time allows.

"
        fi
        ;;
      compile_error|test_failure)
        # Self-correction few-shot: inject past corrections for this error category
        local corrections
        corrections="$(tf_corrections_recall "$category" "$engine" 2>/dev/null)"
        if [[ -n "$corrections" ]]; then
          error_block+="
## ⚠️ Self-Correction: past fixes for $category

Previous similar failures were resolved by:
$corrections

"
        fi
        ;;
      merge_conflict)
        error_block+="
## ⚠️ Previous attempt had a merge conflict

The branch is preserved. Resolve the conflict in the files that conflicted.
The acceptance gate passed last time, so your changes were correct — you just
need to rebase them onto the latest main.

"
        ;;
    esac
  fi

  # Episodic memory: recall similar past episodes (grep-based, ~1ms)
  local episode_block=""
  episode_block="$(tf_episode_recall "$id" 2>/dev/null)"
  if [[ -n "$episode_block" ]]; then
    episode_block="

$episode_block

"
  fi

  # Mission context: project-level context (loaded once at startup, 0 jq per dispatch)
  local mission_block=""
  if [[ -n "${TF_MISSION_CONTEXT:-}" ]]; then
    mission_block="

## Project Context
$TF_MISSION_CONTEXT

"
  fi

  # Select prompt template: use openspec-aware template if OpenSpec metadata present
  local template_dir="$TF_PROMPT_DIR"
  if [[ -n "$task_change" && "$task_change" != "null" ]]; then
    template_dir="$TF_CONFIG_DIR/prompts-openspec"
    [[ -d "$template_dir" ]] || template_dir="$TF_PROMPT_DIR"
  fi

  # Select template based on engine field
  local template_file
  template_file="$(tf_select_template "$id" "$worker")"
  
  tmpl="$(cat "$template_dir/$template_file")"
  tmpl="${tmpl//\{\{TASK_ID\}\}/$id}"
  tmpl="${tmpl//\{\{TASK_TITLE\}\}/$title}"
  tmpl="${tmpl//\{\{ENGINE\}\}/$engine}"
  tmpl="${tmpl//\{\{PLAN_SECTION\}\}/$plan_section}"
  tmpl="${tmpl//\{\{SCOPE_BLOCK\}\}/$scope_block}"
  # Task description (acceptance_prose gives the worker context)
  local task_desc
  task_desc="$(tf_task_field "$id" .acceptance_prose 2>/dev/null || echo '')"
  [[ -z "$task_desc" || "$task_desc" == "null" ]] && task_desc="No additional description. Follow the scope and acceptance gate."
  tmpl="${tmpl//\{\{TASK_DESCRIPTION\}\}/$task_desc}"
  # OpenSpec-specific placeholders
  tmpl="${tmpl//\{\{GROUP\}\}/$task_group}"
  local os_project os_change
  os_project="$(jq -r '._meta.project // "unknown"' "$TASKS_JSON" 2>/dev/null)"
  os_change="$(jq -r '._meta.openspec_change // "unknown"' "$TASKS_JSON" 2>/dev/null)"
  tmpl="${tmpl//\{\{PROJECT\}\}/${task_project:-$os_project}}"
  tmpl="${tmpl//\{\{CHANGE\}\}/${task_change:-$os_change}}"
  
  # Template-specific placeholders for content and scenario workers
  # Get content-specific fields (may be empty - replace with empty string if missing)
  local content_type exam_code exam_slug min_lines min_questions output_file category min_challenges
  content_type="$(tf_task_field "$id" .content_type 2>/dev/null || echo '')"
  [[ "$content_type" == "null" ]] && content_type=""
  tmpl="${tmpl//\{\{CONTENT_TYPE\}\}/$content_type}"
  
  exam_code="$(tf_task_field "$id" .exam_code 2>/dev/null || echo '')"
  [[ "$exam_code" == "null" ]] && exam_code=""
  tmpl="${tmpl//\{\{EXAM_CODE\}\}/$exam_code}"
  
  exam_slug="$(tf_task_field "$id" .exam_slug 2>/dev/null || echo '')"
  [[ "$exam_slug" == "null" ]] && exam_slug=""
  tmpl="${tmpl//\{\{EXAM_SLUG\}\}/$exam_slug}"
  
  min_lines="$(tf_task_field "$id" .min_lines 2>/dev/null || echo '')"
  [[ "$min_lines" == "null" ]] && min_lines=""
  tmpl="${tmpl//\{\{MIN_LINES\}\}/$min_lines}"
  
  min_questions="$(tf_task_field "$id" .min_questions 2>/dev/null || echo '')"
  [[ "$min_questions" == "null" ]] && min_questions=""
  tmpl="${tmpl//\{\{MIN_QUESTIONS\}\}/$min_questions}"
  
  output_file="$(tf_task_field "$id" .output_file 2>/dev/null || echo '')"
  [[ "$output_file" == "null" ]] && output_file=""
  # Fallback to scope[0] if output_file not set
  if [[ -z "$output_file" ]]; then
    output_file="$(tf_task_field "$id" '.scope[0]' 2>/dev/null || echo '')"
    [[ "$output_file" == "null" ]] && output_file=""
  fi
  tmpl="${tmpl//\{\{OUTPUT_FILE\}\}/$output_file}"
  
  category="$(tf_task_field "$id" .category 2>/dev/null || echo '')"
  [[ "$category" == "null" ]] && category=""
  tmpl="${tmpl//\{\{CATEGORY\}\}/$category}"
  
  min_challenges="$(tf_task_field "$id" .min_challenges 2>/dev/null || echo '')"
  [[ "$min_challenges" == "null" ]] && min_challenges=""
  tmpl="${tmpl//\{\{MIN_CHALLENGES\}\}/$min_challenges}"

  # CONTENT_TYPE_SECTION: content-type-specific section for vllm template
  local content_type_section=""
  if [[ "$content_type" == "deep-dive" ]]; then
    content_type_section="- \`{{CATEGORY}}/{{EXAM_SLUG}}-deep-dive.md\` — existing deep dive (for reference, do not copy)"
  elif [[ "$content_type" == "practice-questions" ]]; then
    content_type_section="- \`{{CATEGORY}}/{{EXAM_SLUG}}-practice-questions.md\` — existing practice questions (for reference, do not copy)"
  fi
  tmpl="${tmpl//\{\{CONTENT_TYPE_SECTION\}\}/$content_type_section}"

  # ACCEPT_COMMAND may contain && which breaks ${var//p/r}. Use sed.
  local accept_esc
  accept_esc="$(printf '%s' "$accept" | sed 's/[&\/]/\\&/g')"
  tmpl="$(printf '%s' "$tmpl" | sed "s/{{ACCEPT_COMMAND}}/$accept_esc/g")"
  tmpl="${tmpl//\{\{PREVIOUS_ERROR\}\}/$error_block}"
  tmpl="${tmpl//\{\{EPISODES\}\}/$episode_block}"
  tmpl="${tmpl//\{\{MISSION\}\}/$mission_block}"
  printf '%s' "$tmpl"
}

# tf_dispatch_zombie_guard <task_id>
#   EXIT trap for tf_dispatch_one: if the dispatch subshell dies without a
#   definitive status update (crash between phases), the task would be stuck
#   in "running"/"verifying" forever — invisible to the scheduler. Reset it
#   to "ready" (branch preserved) so the orchestrator can re-dispatch.
#   Idempotent: no-op when the task already reached done/failed.
tf_dispatch_zombie_guard() {
  local id="${1:-}"
  [[ -z "$id" ]] && return 0
  local st
  st="$(tf_status_get "$id" .status 2>/dev/null || echo "")"
  case "$st" in
    running|verifying)
      tf_warn "$id: dispatch subshell died in status '$st' — resetting to ready (zombie guard)"
      tf_status_set "$id" ready '.last_error="dispatch crashed before status update (zombie guard)"' 2>/dev/null || true
      ;;
    *) ;; # done/failed/ready — definitive state, leave it
  esac
  return 0
}

# tf_dispatch_one <task_id> <worker_name>
#   Full lifecycle: worktree → render prompt → run pi → verify → status update.
#   Returns 0 on success (gate passed), non-zero on failure.
tf_dispatch_one() {
  local id="$1" worker="$2"
  # Zombie guard: any crash path that skips the definitive status update
  # (done/failed) must not leave the task stuck in a transient state.
  trap 'tf_dispatch_zombie_guard "$id"' EXIT
  local provider model engine dispatch_timeout log
  # accept is defined in tf_render_prompt(); re-derive it here so the
  # post-gate receipt call (tf_receipt_finish_gate ... "$accept") doesn't hit
  # an unbound variable under `set -u`.
  local accept="$(tf_task_field "$id" .accept 2>/dev/null || echo '')"
  provider="$(tf_worker_field "$worker" .provider)"
  model="$(tf_worker_field "$worker" .model)"
  engine="$(tf_task_field "$id" .engine 2>/dev/null || echo '')"
  dispatch_timeout="$(tf_default dispatch_timeout_s)"; dispatch_timeout="${dispatch_timeout:-3600}"
  # Apply timeout multiplier from category-aware retry (timeout failures)
  local timeout_mult
  timeout_mult="$(tf_status_get "$id" .timeout_multiplier)"
  timeout_mult="${timeout_mult:-1}"
  if (( $(echo "$timeout_mult > 1" | bc -l 2>/dev/null || echo 0) )); then
    dispatch_timeout="$(echo "$dispatch_timeout * $timeout_mult" | bc -l 2>/dev/null | cut -d. -f1)"
    tf_info "$id: using scaled timeout ${dispatch_timeout}s (multiplier: $timeout_mult)"
  fi
  log="$TF_LOG_DIR/$id.dispatch.log"

  # Acceptance gate command — already derived above with || echo '' fallback.
  # Used by the receipt ledger and cross-vendor verify (dispatch.sh:266).
  local branch="$TF_BRANCH_PREFIX/$id"
  local tmp
  tmp="$(mktemp)"
  jq --arg id "$id" --arg worker "$worker" --arg branch "$branch" \
    --arg now "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    '.[$id].status="running" | .[$id].worker=$worker | .[$id].branch=$branch
     | .[$id].started_at=$now | .[$id].next_retry_at=null' \
    "$STATUS_JSON" > "$tmp"
  tf_locked_mv "$tmp" "$STATUS_JSON"

  tf_info "$id: dispatching to worker=$worker ($provider/$model)"

  # Record dispatch start in receipt ledger
  tf_receipt_begin "$id" "$worker" "$provider" "$model" "$branch"

  # 1. Create worktree. If this is a retry of a merge-conflict failure, reuse
  #    the preserved branch so the agent resolves the conflict instead of
  #    redoing all its work from scratch.
  local wt keep_branch=""
  local base="${TF_BASE_BRANCH}"
  local prev_err attempts
  prev_err="$(tf_status_get "$id" .last_error 2>/dev/null || echo "")"
  attempts="$(tf_status_get "$id" .attempts 2>/dev/null || echo 0)"
  
  # Check if this is a speculative dispatch (all deps except one running dep are done)
  if tf_is_speculatively_ready "$id"; then
    local base_dep
    base_dep="$(tf_speculative_base_dep "$id")"
    if [[ -n "$base_dep" ]]; then
      base="$TF_BRANCH_PREFIX/$base_dep"
      tf_info "$id: SPECULATIVE dispatch based on running dependency $base_dep (branch: $base)"
    fi
  fi
  
  if [[ "$attempts" -gt 0 && "$prev_err" == *"merge"* ]]; then
    keep_branch="--keep-branch"
  fi
  wt="$(tf_worktree_create "$id" "$base" $keep_branch)" || {
    tf_fail_task "$id" "worktree creation failed"
    return 1
  }

  # 2. Render prompt (includes error feedback on retries)
  local prompt_file
  prompt_file="$TF_STATE_DIR/$id.prompt.md"
  # Resolve to absolute path (TF_STATE_DIR may be relative)
  [[ "$prompt_file" != /* ]] && prompt_file="$(cd "$(dirname "$prompt_file")" 2>/dev/null && pwd)/$(basename "$prompt_file")"
  tf_render_prompt "$id" "$worker" > "$prompt_file"

  # 3. Run pi headless inside the worktree
  {
    echo "=== $id dispatch ==="
    echo "worker: $worker ($provider/$model)"
    echo "worktree: $wt"
    echo "branch: $branch"
    echo "started: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "attempt: $(tf_status_get "$id" .attempts)"
    echo "============================================"
  } > "$log"

  local rc=0
  if [[ "$provider" == "vllm" ]]; then
    # Direct Python call to vllm endpoint (bypasses pi entirely)
    local output_file
    output_file="$(tf_task_field "$id" '.scope[0]' 2>/dev/null || echo '')"
    local task_min_lines
    task_min_lines="$(tf_task_field "$id" .min_lines 2>/dev/null || echo '')"
    [[ "$task_min_lines" == "null" || -z "$task_min_lines" ]] && task_min_lines=
    local max_tokens=49152
    if [[ -n "$task_min_lines" && "$task_min_lines" -gt 500 ]]; then
      max_tokens=65536
    fi
    (
      cd "$wt" || exit 127
      "$TF_LIB_DIR/vllm-worker.py" \
        --prompt "$prompt_file" \
        --output "$output_file" \
        --model "$model" \
        --max-tokens "$max_tokens"
    ) >> "$log" 2>&1 || rc=$?
  else
    (
      cd "$wt" || exit 127
      timeout "$dispatch_timeout" pi \
        --provider "$provider" \
        --model "$model" \
        -p "@$prompt_file"
    ) >> "$log" 2>&1 || rc=$?
  fi

  if [[ $rc -ne 0 ]]; then
    local reason
    if [[ $rc -eq 124 ]]; then reason="dispatch timed out after ${dispatch_timeout}s"
    else reason="pi exited $rc"; fi
    tf_warn "$id: $reason — attempting acceptance gate anyway (worker may have committed)"
  fi

  # Record dispatch completion in receipt ledger
  tf_receipt_finish_dispatch "$id" "$log" "$rc"

  # 3b. No-op detection: check if the worker actually modified any scope files.
  #     If nothing changed, fail immediately rather than wasting gate time.
  #     We compare the worktree's HEAD against the base (main) to detect
  #     both uncommitted changes AND committed changes.
  local base_ref
  base_ref="$(cd "$TF_REPO_DIR" && git rev-parse --verify "${TF_BASE_BRANCH}" 2>/dev/null)"
  local wt_head
  wt_head="$(cd "$wt" && git rev-parse --verify HEAD 2>/dev/null)"
  local changed_files untracked_files
  changed_files="$(cd "$wt" && git diff --name-only "$base_ref" 2>/dev/null)"
  untracked_files="$(cd "$wt" && git ls-files --others --exclude-standard 2>/dev/null)"
  local committed_changes=""
  if [[ "$wt_head" != "$base_ref" ]]; then
    # Branch has commits — check for actual file changes
    committed_changes="$(cd "$wt" && git diff --name-only "$base_ref" HEAD 2>/dev/null)"
  fi
  if [[ -z "$changed_files" && -z "$untracked_files" && -z "$committed_changes" ]]; then
    tf_fail_task "$id" "no changes: LLM did not modify any files in scope (dispatch log: $TF_LOG_DIR/$id.dispatch.log)"
    # Write error.json for retry feedback
    mkdir -p "$TF_LOG_DIR"
    echo '{"category":"no_op","summary":"LLM produced no tool calls or file modifications","classified_at":"'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'"}' > "$TF_LOG_DIR/$id.error.json"
    tf_receipt_close "$id" "failed" "no_op: no files modified"
    tf_worktree_remove "$id" --force
    tf_worktree_delete_branch "$id"
    return 1
  fi
  tf_info "$id: worker modified $(echo "$changed_files $untracked_files $committed_changes" | wc -w) file(s)"

  # 4. Verify (acceptance gate) — now with error classification
  tf_status_set "$id" verifying
  local verdict
  verdict="$(tf_verify "$id" "$wt")" || true

  # Record gate outcome in receipt ledger
  tf_receipt_finish_gate "$id" "$verdict" "$accept"

  # 5. Advisory scope check
  tf_verify_scope "$id" "$wt" >>"$TF_LOG_DIR/$id.scope.log" 2>&1 || true

  # 6. Commit if worker forgot (best-effort) — only in-scope files
  if [[ "$verdict" == PASS* ]]; then
    (cd "$wt" && git add -A && git diff --cached --quiet || \
       git commit -q -m "feat($id): $(tf_task_field "$id" .title)" 2>/dev/null) || true
  fi

  # 6b. Cross-vendor verify gate (if configured)
  #     After the primary gate passes, optionally dispatch verification to a
  #     DIFFERENT provider/model. Independent model + independent context =
  #     structurally impossible to fool with same-model self-agreement.
  local verify_worker verify_verdict
  verify_worker="$(tf_task_field "$id" .verify_worker 2>/dev/null || echo '')"
  [[ "$verify_worker" == "null" ]] && verify_worker=""
  if [[ "$verdict" == PASS* && -n "$verify_worker" ]]; then
    tf_info "$id: cross-vendor verify gate → $verify_worker"
    tf_status_set "$id" verifying "(.worker=\"$verify_worker\")"
    verify_verdict="$(tf_cross_vendor_verify "$id" "$wt" "$verify_worker")" || verify_verdict="FAIL: verify dispatch error"
    tf_receipt_finish_gate "$id" "$verify_verdict" "cross-vendor:$verify_worker"
    if [[ "$verify_verdict" != PASS* ]]; then
      tf_fail_task "$id" "cross-vendor verify gate: $verify_verdict"
      tf_receipt_close "$id" "failed" "cross_vendor_verify_failed"
      tf_worktree_remove "$id" --force
      tf_worktree_delete_branch "$id"
      return 1
    fi
    tf_info "$id: cross-vendor verify PASS"
  fi

  # 7. Status update + merge
  if [[ "$verdict" == PASS* ]]; then
    # Constitution check (deterministic pre-merge checks, if enabled)
    if [[ "${TF_CONSTITUTION:-0}" == "1" ]]; then
      if ! tf_constitution_check "$id" "$wt"; then
        tf_warn "$id: constitution check failed — merging anyway (advisory)"
        tf_log_decision "$id" "CONSTITUTION" "constitution check failed (advisory)"
      fi
    fi

    # Trust score evaluation (pure arithmetic, ~0ms)
    local scope_violations=0
    local scope_log="$TF_LOG_DIR/$id.scope.log"
    if [[ -f "$scope_log" ]]; then
      scope_violations="$(grep -c 'OUT-OF-SCOPE' "$scope_log" 2>/dev/null)"
      [[ -z "$scope_violations" ]] && scope_violations=0
    fi
    local gate_passed=1
    [[ "$verdict" != PASS* ]] && gate_passed=0
    local trust_score trust_bucket
    trust_score="$(tf_trust_score "$id" "$gate_passed" "$([[ $scope_violations -eq 0 ]] && echo 1 || echo 0)" "$attempts" "$worker" "$engine")"
    trust_bucket="$(tf_trust_bucket "$trust_score")"
    tf_log_dispatch "$id" "trust" "score=$trust_score bucket=$trust_bucket"
    tf_log_decision "$id" "TRUST" "score=$trust_score bucket=$trust_bucket" "gate=$gate_passed scope_ok=$([[ $scope_violations -eq 0 ]] && echo 1 || echo 0) retries=$attempts"

    if tf_worktree_merge "$id"; then
      tf_done_task "$id"
      tf_receipt_close "$id" "done"
      # Episodic memory: record successful completion
      local wall_clock
      wall_clock="$(tf_receipt_wall_clock "$id" 2>/dev/null || echo 0)"
      tf_episode_record "$id" "$worker" 1 "$wall_clock" ""
      # Self-correction: if this was a successful retry, record the correction
      if [[ "$attempts" -gt 0 ]]; then
        local prev_cat
        prev_cat="$(tf_status_get "$id" .error_category 2>/dev/null || echo "")"
        if [[ -n "$prev_cat" && "$prev_cat" != "none" ]]; then
          local correction
          correction="$(tf_corrections_extract "$id" "$wt" "$prev_cat")"
          tf_corrections_record "$prev_cat" "$engine" "$correction" "$id"
        fi
      fi
      tf_log_dispatch "$id" "merge" "trust=$trust_score"
      tf_worktree_remove "$id"
      tf_worktree_delete_branch "$id"
      return 0
    else
      # Merge failed (rebase conflicted). KEEP the branch + worktree so the
      # work is preserved; report which files conflicted for the retry prompt.
      local conflicts
      conflicts="$(tf_worktree_conflicts "$id" | tr '\n' ' ')"
      if [[ -n "$conflicts" ]]; then
        tf_fail_task "$id" "merge conflict in: $conflicts (gate passed but main diverged; branch kept for retry)"
      else
        tf_fail_task "$id" "merge failed (gate passed but main diverged; branch kept for retry)"
      fi
      tf_receipt_close "$id" "failed" "merge_conflict"
      tf_log_dispatch "$id" "merge_fail" "conflicts: $conflicts"
      tf_info "$id: preserved worktree + branch for retry or manual resolution"
      return 1
    fi
  else
    tf_fail_task "$id" "acceptance gate: $verdict"
    tf_receipt_close "$id" "failed" "gate_failed"
    # Episodic memory: record failed attempt
    local err_cat
    err_cat="$(tf_get_error_category "$id" 2>/dev/null || echo "unknown")"
    tf_episode_record "$id" "$worker" 0 0 "$err_cat"
    tf_log_dispatch "$id" "gate_fail" "verdict=$verdict category=$err_cat"
    tf_log_decision "$id" "GATE_FAIL" "verdict=$verdict" "category=$err_cat worker=$worker"
    tf_worktree_remove "$id" --force
    tf_worktree_delete_branch "$id"
    return 1
  fi
}

# tf_dispatch_one_dryrun <task_id> <worker_name>
#   Prints what would happen without running pi. For testing.
tf_dispatch_one_dryrun() {
  local id="$1" worker="$2"
  local provider model accept
  provider="$(tf_worker_field "$worker" .provider)"
  model="$(tf_worker_field "$worker" .model)"
  accept="$(tf_task_field "$id" .accept)"
  local attempts
  attempts="$(tf_status_get "$id" .attempts 2>/dev/null || echo 0)"
  echo "DRY-RUN $id → worker=$worker ($provider/$model) (attempt $((attempts+1)))"
  echo "  accept: $accept"
  echo "  scope:  $(tf_task_field "$id" '.scope | length') path(s)"
  if [[ "$attempts" -gt 0 ]]; then
    echo "  RETRY: category=$(tf_get_error_category "$id") summary=$(tf_get_error_summary "$id")"
  fi
  echo "  prompt: $TF_STATE_DIR/$id.prompt.md"
  tf_render_prompt "$id" "$worker" | head -5
  echo "  ..."
}

# tf_cross_vendor_verify <task_id> <worktree_path> <verify_worker_name>
#   Runs an independent verification using a different provider/model.
#   Returns "PASS" or "FAIL: <reason>". Does NOT run the full acceptance
#   gate (tests) again — instead, asks the verify agent to review the diff
#   and task spec for correctness.
tf_cross_vendor_verify() {
  local id="$1" wt="$2" vw="$3"
  local vprovider vmodel verify_timeout verify_log
  vprovider="$(tf_worker_field "$vw" .provider)"
  vmodel="$(tf_worker_field "$vw" .model)"
  verify_timeout="$(tf_default verify_cross_vendor_timeout_s)"; verify_timeout="${verify_timeout:-600}"
  verify_log="$TF_LOG_DIR/$id.cross-verify.log"

  # Build the verify prompt: task spec + diff + primary gate output
  local diff_content gate_output verify_prompt
  diff_content="$(cd "$wt" && git diff "${TF_BASE_BRANCH}"...HEAD 2>/dev/null | head -500)"
  gate_output="$(tail -30 "$TF_LOG_DIR/$id.verify.log" 2>/dev/null)"

  local task_spec accept_cmd
  task_spec="$(tf_task_field "$id" .acceptance_prose 2>/dev/null || echo '')"
  accept_cmd="$(tf_task_field "$id" .accept)"
  [[ -z "$task_spec" || "$task_spec" == "null" ]] && task_spec="$accept_cmd"

  verify_prompt="You are a code reviewer. Review the following changes against the task specification.

## Task Specification
$task_spec

## Changes (diff from main)
\`\`\`diff
${diff_content:-<no diff output>}
\`\`\`

## Primary Acceptance Gate Output
${gate_output:-<no gate output>}

## Your Task
1. Verify the changes implement the specification correctly
2. Check for unintended side effects or scope creep
3. Verify no security vulnerabilities or obvious bugs
4. If everything is correct, run: true
5. If you find problems, run: false

You MUST run either true or false as your final command."

  local verify_prompt_file="$TF_STATE_DIR/$id.cross-verify.md"
  echo "$verify_prompt" > "$verify_prompt_file"

  {
    echo "=== $id cross-vendor verify ==="
    echo "verify_worker: $vw ($vprovider/$vmodel)"
    echo "started: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "============================================"
  } > "$verify_log"

  local rc=0
  (
    cd "$wt" || exit 127
    timeout "$verify_timeout" pi \
      --provider "$vprovider" \
      --model "$vmodel" \
      -p "@$verify_prompt_file"
  ) >> "$verify_log" 2>&1 || rc=$?

  if [[ $rc -eq 0 ]]; then
    echo "PASS"
    return 0
  else
    local reason
    if [[ $rc -eq 124 ]]; then reason="cross-vendor verify timed out after ${verify_timeout}s"
    else reason="cross-vendor verify exited $rc"
    fi
    echo "FAIL: $reason"
    return 1
  fi
}
